import {
  Bot,
  Calendar,
  CalendarClock,
  Check,
  Clock,
  Code,
  Command,
  Database,
  Download,
  Github,
  Hourglass,
  Keyboard,
  LayoutGrid,
  Lightbulb,
  Link2,
  ListChecks,
  Monitor,
  RefreshCw,
  Repeat,
  Server,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Terminal,
  Timer,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/content/marketing/types";

/** Icon names that content modules can use (they can't import React). */
export const ICONS: Record<IconName, LucideIcon> = {
  bot: Bot,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  check: Check,
  clock: Clock,
  code: Code,
  command: Command,
  database: Database,
  download: Download,
  github: Github,
  hourglass: Hourglass,
  keyboard: Keyboard,
  layout: LayoutGrid,
  lightbulb: Lightbulb,
  link: Link2,
  list: ListChecks,
  monitor: Monitor,
  refresh: RefreshCw,
  repeat: Repeat,
  server: Server,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  terminal: Terminal,
  timer: Timer,
  zap: Zap,
};
