/**
 * Product media that blog posts embed with <Shot>, <Clip> and <DemoVideo>.
 *
 * blog-media.json is generated by the media recorder; edit the recorder, not
 * the JSON. Files live under /blog-media/ with content-hashed names, so
 * server.ts caches them for a year. Only relative imports here: the build
 * scripts in scripts/ import this file too.
 */

import data from "./blog-media.json";

export type Themed<T> = { light: T; dark: T };

/** A screenshot with one WebP per theme. */
export type ShotMedia = { width: number; height: number } & Themed<string>;

/** A short silent loop with one MP4 + poster per theme. */
export type ClipMedia = {
  width: number;
  height: number;
  /** Seconds */
  duration: number;
} & Themed<{ mp4: string; poster: string }>;

/** A narrated walkthrough. */
export type VideoMedia = {
  width: number;
  height: number;
  /** Seconds */
  duration: number;
  mp4: string;
  poster: string;
  /** WebVTT file */
  captions?: string;
  title: string;
  description: string;
  /** ISO date, e.g. 2026-09-24 */
  uploadDate: string;
};

export interface BlogMedia {
  shots: Record<string, ShotMedia>;
  clips: Record<string, ClipMedia>;
  videos: Record<string, VideoMedia>;
}

// Cast, not annotate: the recorder rewrites the JSON while it works, and a
// half-written entry must not fail the type check. Components guard at runtime.
export const BLOG_MEDIA = data as unknown as BlogMedia;

/** 135 -> "PT2M15S" (ISO 8601 duration, as schema.org expects). */
export function isoDuration(seconds: number): string {
  const total = Math.max(0, Math.round(seconds));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  return `PT${h ? `${h}H` : ""}${m ? `${m}M` : ""}${s || total === 0 ? `${s}S` : ""}`;
}

/** 135 -> "2:15" */
export function clockDuration(seconds: number): string {
  const total = Math.max(0, Math.round(seconds));
  return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`;
}
